name: riceguard 
description: "A Flutter app for monitoring rice storage conditions."
publish_to: 'none'

version: 1.0.1+2 # Already updated in the previous step

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true